name: Build macOS .app

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install py2app
        run: |
          python3 -m pip install --upgrade pip
          pip3 install py2app

      - name: Build app
        run: |
          python3 setup.py py2app

      - name: Upload .app
        uses: actions/upload-artifact@v4
        with:
          name: Text-Tool
          path: dist/*.app
